name: pre-commit

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  all-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
